name: GitHub Actions Demo
run-name: ${{ github.actor }} is deploying the app with GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: copy files
        uses: appleboy/scp-action@v0.1.7
        with:
          host: 51.75.20.206
          username: root
          port: 22
          key: ${{ secrets.ID_RSA }}
          source: "."
          target: "/var/www/portefolio"
          rm: true
