name: GitHub Actions Demo
run-name: ${{ github.actor }} is deploying the app with GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Check out repository code
        uses: actions/checkout@v4
      - run: ls
